name: bump version

on: workflow_dispatch

jobs:
  release:
    name: Bump Version
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt-get install python3-venv make
        pip3 install --upgrade pip wheel
    - run: echo bldr_version=$(make bump-version) | tee --append $GITHUB_ENV
    - uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "Bump version to ${{ env.bldr_version }}"
        title: "Bump version to ${{ env.bldr_version }}"
        body:
        branch: "bump-version-to-v${{ env.bldr_version }}"
        delete-branch: true
        token: ${{ secrets.GITHUB_TOKEN }}
