name: build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  lint:
    name: Coding style and linting checks
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt-get install python3-venv make
        pip3 install --upgrade pip
    - run: make dev
    - run: make cs lint

  test:
    name: Test with docker image ${{ matrix.docker-image }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        docker-image: ['ubuntu:xenial', 'ubuntu:bionic', 'ubuntu:focal', 'debian:bullseye']

    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt-get install python3-venv make
        pip3 install --upgrade pip
    - run: make DOCKER_IMAGE=${{ matrix.docker-image }} check-docker-image
