name: release

on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - run: pip3 install --upgrade pip wheel twine
    - run: make release
    - run: make release-test
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true
    - run: echo bldr_version=$(cat bldr/VERSION) | tee --append $GITHUB_ENV
    - uses: negz/create-tag@v1
      with:
        version: "v${{ env.bldr_version }}"
        token: ${{ secrets.GITHUB_TOKEN }}
